name = "Shellux"
grammar = "bash"
path_suffixes = ["sx", "shx"]
line_comments = ["# "]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])>` \n\t"

[brackets]
"(" = ")"
"{" = "}"
"[" = "]"
"\"" = "\""
"'" = "'"
"`" = "`"
